name: NPM Start Check

on:
  pull_request:
    types: [opened]

jobs:
  npm_start:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run npm start
      run: npm start

    - name: Check for errors
      run: |
        if [ $? -eq 0 ]; then
          echo "npm start succeeded"
        else
          echo "npm start failed. Check for errors."
          exit 1
        fi
